make ejecutar:
	gcc multi_digit.c 
	gcc multi_digit.c -o multi_digit 
	gcc -S -O3 -fno-asynchronous-unwind-tables multi_digit.c

	gcc newlines.c 
	gcc newlines.c -o newlines 
	gcc -S -O3 -fno-asynchronous-unwind-tables newlines.c


	gcc no_newlines.c 
	gcc no_newlines.c -o no_newlines 
	gcc -S -O3 -fno-asynchronous-unwind-tables no_newlines.c

	gcc return_0.c 
	gcc return_0.c -o return_0 
	gcc -S -O3 -fno-asynchronous-unwind-tables return_0.c

	gcc return_2.c 
	gcc return_2.c -o return_2 
	gcc -S -O3 -fno-asynchronous-unwind-tables return_2.c

	gcc spaces.c 
	gcc spaces.c -o spaces 
	gcc -S -O3 -fno-asynchronous-unwind-tables spaces.c

	gcc tabulador.c 
	gcc tabulador.c -o tabulador 
	gcc -S -O3 -fno-asynchronous-unwind-tables tabulador.c


	gcc return002.c 
	gcc return002.c -o return002 
	gcc -S -O3 -fno-asynchronous-unwind-tables return002.c